spring:
  profiles:
    active:
    - dev
  
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-01-config-client
    
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka
 
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-01-config-client
    
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7002.com:7002/eureka
   