spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev
  application:
    name: springcloud-01-config-dev
    
---
spring:
  profiles: test
  application:
    name: springcloud-01-config-test
  