spring:
  profiles:
    active:
    - dev
---
server:
  port: 9001
  
 
mybatis:
  config-location: classpath:mybatis/mybaits.cfg.xml
  type-aliases-package: com.example.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  profiles: dev
  application:
    name: sprigcloud-01-provider
   
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud01
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 20  
 
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka
  instance:
    instance-id: springcolud-01-provider9001
    prefer-ip-address: true
    
    
#info界面展示的key-value的json值
info:
  app.name: springcloud-provider-9001
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 9001
  
 
mybatis:
  config-location: classpath:mybatis/mybaits.cfg.xml
  type-aliases-package: com.example.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  profiles: test
  application:
    name: sprigcloud-01-provider
   
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud02
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-total: 5
      min-idle: 5
      max-wait-millis: 20  
 
eureka:
  client:
    service-url:
      defaultZone: http://springcloud-eureka7001.com:7001/eureka
  instance:
    instance-id: springcolud-01-provider9001
    prefer-ip-address: true
    
    
#info界面展示的key-value的json值
info:
  app.name: springcloud-provider-9001
  build.artifactId: $project.artifactId$
  build.version: $project.version$